import type { Protocol } from './types';

/** The 6 preset fasting protocols */
export const PRESET_PROTOCOLS: Protocol[] = [
  {
    id: '16:8',
    name: 'Lean Gains (16:8)',
    fastingHours: 16,
    eatingHours: 8,
    description: 'Fast 16 hours, eat within an 8-hour window. Most popular protocol for beginners.',
    isCustom: false,
    isDefault: true,
    sortOrder: 1,
  },
  {
    id: '18:6',
    name: 'Daily 18:6',
    fastingHours: 18,
    eatingHours: 6,
    description: 'Fast 18 hours, eat within a 6-hour window. Moderate intensity.',
    isCustom: false,
    isDefault: false,
    sortOrder: 2,
  },
  {
    id: '20:4',
    name: 'Warrior (20:4)',
    fastingHours: 20,
    eatingHours: 4,
    description: 'Fast 20 hours, eat within a 4-hour window. One main meal with snacks.',
    isCustom: false,
    isDefault: false,
    sortOrder: 3,
  },
  {
    id: '23:1',
    name: 'OMAD (23:1)',
    fastingHours: 23,
    eatingHours: 1,
    description: 'One Meal A Day. Fast 23 hours, single eating hour.',
    isCustom: false,
    isDefault: false,
    sortOrder: 4,
  },
  {
    id: '36:0',
    name: 'Alternate Day (36h)',
    fastingHours: 36,
    eatingHours: 0,
    description: 'Full 36-hour fast. Skip an entire day of eating.',
    isCustom: false,
    isDefault: false,
    sortOrder: 5,
  },
  {
    id: '48:0',
    name: 'Extended (48h)',
    fastingHours: 48,
    eatingHours: 0,
    description: 'Full 48-hour fast. Two days without eating.',
    isCustom: false,
    isDefault: false,
    sortOrder: 6,
  },
];
