import type { CatalogEntry } from './types';

/**
 * Pre-populated subscription catalog with 200+ services.
 * Prices are in cents and reflect typical US pricing as of 2026.
 */
export const CATALOG_ENTRIES: readonly CatalogEntry[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // ENTERTAINMENT (55 entries)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'netflix-standard',
    name: 'Netflix Standard',
    defaultPrice: 1549,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'netflix',
    url: 'https://www.netflix.com',
  },
  {
    id: 'netflix-premium',
    name: 'Netflix Premium',
    defaultPrice: 2299,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'netflix',
    url: 'https://www.netflix.com',
  },
  {
    id: 'netflix-standard-ads',
    name: 'Netflix Standard with Ads',
    defaultPrice: 799,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'netflix',
    url: 'https://www.netflix.com',
  },
  {
    id: 'spotify-premium',
    name: 'Spotify Premium',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'spotify',
    url: 'https://www.spotify.com',
  },
  {
    id: 'spotify-duo',
    name: 'Spotify Premium Duo',
    defaultPrice: 1699,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'spotify',
    url: 'https://www.spotify.com',
  },
  {
    id: 'spotify-family',
    name: 'Spotify Premium Family',
    defaultPrice: 1999,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'spotify',
    url: 'https://www.spotify.com',
  },
  {
    id: 'youtube-premium',
    name: 'YouTube Premium',
    defaultPrice: 1399,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'youtube',
    url: 'https://www.youtube.com/premium',
  },
  {
    id: 'youtube-premium-family',
    name: 'YouTube Premium Family',
    defaultPrice: 2299,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'youtube',
    url: 'https://www.youtube.com/premium',
  },
  {
    id: 'youtube-music',
    name: 'YouTube Music Premium',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'youtube-music',
    url: 'https://music.youtube.com',
  },
  {
    id: 'disney-plus',
    name: 'Disney+ (No Ads)',
    defaultPrice: 1599,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'disney-plus',
    url: 'https://www.disneyplus.com',
  },
  {
    id: 'disney-plus-ads',
    name: 'Disney+ (With Ads)',
    defaultPrice: 899,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'disney-plus',
    url: 'https://www.disneyplus.com',
  },
  {
    id: 'hulu',
    name: 'Hulu (With Ads)',
    defaultPrice: 899,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'hulu',
    url: 'https://www.hulu.com',
  },
  {
    id: 'hulu-no-ads',
    name: 'Hulu (No Ads)',
    defaultPrice: 1899,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'hulu',
    url: 'https://www.hulu.com',
  },
  {
    id: 'hbo-max',
    name: 'Max (Ad-Free)',
    defaultPrice: 1699,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'max',
    url: 'https://www.max.com',
  },
  {
    id: 'hbo-max-ads',
    name: 'Max (With Ads)',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'max',
    url: 'https://www.max.com',
  },
  {
    id: 'hbo-max-ultimate',
    name: 'Max Ultimate (4K)',
    defaultPrice: 2099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'max',
    url: 'https://www.max.com',
  },
  {
    id: 'amazon-prime-video',
    name: 'Amazon Prime Video',
    defaultPrice: 899,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'prime-video',
    url: 'https://www.amazon.com/primevideo',
  },
  {
    id: 'apple-tv-plus',
    name: 'Apple TV+',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'apple-tv',
    url: 'https://tv.apple.com',
  },
  {
    id: 'apple-music',
    name: 'Apple Music',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'apple-music',
    url: 'https://music.apple.com',
  },
  {
    id: 'apple-music-family',
    name: 'Apple Music Family',
    defaultPrice: 1699,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'apple-music',
    url: 'https://music.apple.com',
  },
  {
    id: 'apple-one-individual',
    name: 'Apple One Individual',
    defaultPrice: 1995,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'apple',
    url: 'https://www.apple.com/apple-one',
  },
  {
    id: 'apple-one-family',
    name: 'Apple One Family',
    defaultPrice: 2595,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'apple',
    url: 'https://www.apple.com/apple-one',
  },
  {
    id: 'apple-one-premier',
    name: 'Apple One Premier',
    defaultPrice: 3795,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'apple',
    url: 'https://www.apple.com/apple-one',
  },
  {
    id: 'peacock-premium',
    name: 'Peacock Premium',
    defaultPrice: 799,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'peacock',
    url: 'https://www.peacocktv.com',
  },
  {
    id: 'peacock-premium-plus',
    name: 'Peacock Premium Plus',
    defaultPrice: 1399,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'peacock',
    url: 'https://www.peacocktv.com',
  },
  {
    id: 'paramount-plus',
    name: 'Paramount+ (Essential)',
    defaultPrice: 799,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'paramount-plus',
    url: 'https://www.paramountplus.com',
  },
  {
    id: 'paramount-plus-premium',
    name: 'Paramount+ with Showtime',
    defaultPrice: 1399,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'paramount-plus',
    url: 'https://www.paramountplus.com',
  },
  {
    id: 'discovery-plus',
    name: 'Discovery+',
    defaultPrice: 599,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'discovery-plus',
    url: 'https://www.discoveryplus.com',
  },
  {
    id: 'crunchyroll',
    name: 'Crunchyroll Premium',
    defaultPrice: 799,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'crunchyroll',
    url: 'https://www.crunchyroll.com',
  },
  {
    id: 'crunchyroll-mega',
    name: 'Crunchyroll Mega Fan',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'crunchyroll',
    url: 'https://www.crunchyroll.com',
  },
  {
    id: 'tidal-hifi',
    name: 'TIDAL HiFi',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'tidal',
    url: 'https://tidal.com',
  },
  {
    id: 'tidal-hifi-plus',
    name: 'TIDAL HiFi Plus',
    defaultPrice: 1999,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'tidal',
    url: 'https://tidal.com',
  },
  {
    id: 'amazon-music-unlimited',
    name: 'Amazon Music Unlimited',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'amazon-music',
    url: 'https://music.amazon.com',
  },
  {
    id: 'deezer-premium',
    name: 'Deezer Premium',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'deezer',
    url: 'https://www.deezer.com',
  },
  {
    id: 'pandora-plus',
    name: 'Pandora Plus',
    defaultPrice: 549,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'pandora',
    url: 'https://www.pandora.com',
  },
  {
    id: 'pandora-premium',
    name: 'Pandora Premium',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'pandora',
    url: 'https://www.pandora.com',
  },
  {
    id: 'siriusxm',
    name: 'SiriusXM Streaming',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'siriusxm',
    url: 'https://www.siriusxm.com',
  },
  {
    id: 'audible-premium',
    name: 'Audible Premium Plus',
    defaultPrice: 1495,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'audible',
    url: 'https://www.audible.com',
  },
  {
    id: 'audible-plus',
    name: 'Audible Plus',
    defaultPrice: 799,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'audible',
    url: 'https://www.audible.com',
  },
  {
    id: 'kindle-unlimited',
    name: 'Kindle Unlimited',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'kindle',
    url: 'https://www.amazon.com/kindleunlimited',
  },
  {
    id: 'scribd',
    name: 'Scribd',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'scribd',
    url: 'https://www.scribd.com',
  },
  {
    id: 'xbox-game-pass-core',
    name: 'Xbox Game Pass Core',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'xbox',
    url: 'https://www.xbox.com/gamepass',
  },
  {
    id: 'xbox-game-pass-ultimate',
    name: 'Xbox Game Pass Ultimate',
    defaultPrice: 1999,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'xbox',
    url: 'https://www.xbox.com/gamepass',
  },
  {
    id: 'playstation-plus-essential',
    name: 'PlayStation Plus Essential',
    defaultPrice: 7999,
    billingCycle: 'annual',
    category: 'entertainment',
    iconKey: 'playstation',
    url: 'https://www.playstation.com/ps-plus',
  },
  {
    id: 'playstation-plus-premium',
    name: 'PlayStation Plus Premium',
    defaultPrice: 17999,
    billingCycle: 'annual',
    category: 'entertainment',
    iconKey: 'playstation',
    url: 'https://www.playstation.com/ps-plus',
  },
  {
    id: 'nintendo-switch-online',
    name: 'Nintendo Switch Online',
    defaultPrice: 3999,
    billingCycle: 'annual',
    category: 'entertainment',
    iconKey: 'nintendo',
    url: 'https://www.nintendo.com/switch/online',
  },
  {
    id: 'twitch-turbo',
    name: 'Twitch Turbo',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'twitch',
    url: 'https://www.twitch.tv/turbo',
  },
  {
    id: 'espn-plus',
    name: 'ESPN+',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'espn',
    url: 'https://plus.espn.com',
  },
  {
    id: 'fubo-pro',
    name: 'FuboTV Pro',
    defaultPrice: 7999,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'fubo',
    url: 'https://www.fubo.tv',
  },
  {
    id: 'youtube-tv',
    name: 'YouTube TV',
    defaultPrice: 7299,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'youtube-tv',
    url: 'https://tv.youtube.com',
  },
  {
    id: 'sling-tv-orange',
    name: 'Sling TV Orange',
    defaultPrice: 4000,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'sling',
    url: 'https://www.sling.com',
  },
  {
    id: 'mubi',
    name: 'MUBI',
    defaultPrice: 1499,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'mubi',
    url: 'https://mubi.com',
  },
  {
    id: 'criterion-channel',
    name: 'Criterion Channel',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'criterion',
    url: 'https://www.criterionchannel.com',
  },
  {
    id: 'shudder',
    name: 'Shudder',
    defaultPrice: 699,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'shudder',
    url: 'https://www.shudder.com',
  },
  {
    id: 'starz',
    name: 'STARZ',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'starz',
    url: 'https://www.starz.com',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // PRODUCTIVITY (42 entries)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'chatgpt-plus',
    name: 'ChatGPT Plus',
    defaultPrice: 2000,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'chatgpt',
    url: 'https://chat.openai.com',
  },
  {
    id: 'chatgpt-pro',
    name: 'ChatGPT Pro',
    defaultPrice: 20000,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'chatgpt',
    url: 'https://chat.openai.com',
  },
  {
    id: 'claude-pro',
    name: 'Claude Pro',
    defaultPrice: 2000,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'claude',
    url: 'https://claude.ai',
  },
  {
    id: 'claude-max',
    name: 'Claude Max',
    defaultPrice: 10000,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'claude',
    url: 'https://claude.ai',
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot Pro',
    defaultPrice: 1000,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'github',
    url: 'https://github.com/features/copilot',
  },
  {
    id: 'microsoft-365-personal',
    name: 'Microsoft 365 Personal',
    defaultPrice: 9999,
    billingCycle: 'annual',
    category: 'productivity',
    iconKey: 'microsoft-365',
    url: 'https://www.microsoft.com/microsoft-365',
  },
  {
    id: 'microsoft-365-family',
    name: 'Microsoft 365 Family',
    defaultPrice: 12999,
    billingCycle: 'annual',
    category: 'productivity',
    iconKey: 'microsoft-365',
    url: 'https://www.microsoft.com/microsoft-365',
  },
  {
    id: 'google-one-100gb',
    name: 'Google One 100GB',
    defaultPrice: 299,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'google-one',
    url: 'https://one.google.com',
  },
  {
    id: 'google-one-2tb',
    name: 'Google One 2TB',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'google-one',
    url: 'https://one.google.com',
  },
  {
    id: 'google-workspace-starter',
    name: 'Google Workspace Business Starter',
    defaultPrice: 700,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'google-workspace',
    url: 'https://workspace.google.com',
  },
  {
    id: 'icloud-plus-50gb',
    name: 'iCloud+ 50GB',
    defaultPrice: 99,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'icloud',
    url: 'https://www.apple.com/icloud',
  },
  {
    id: 'icloud-plus-200gb',
    name: 'iCloud+ 200GB',
    defaultPrice: 299,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'icloud',
    url: 'https://www.apple.com/icloud',
  },
  {
    id: 'icloud-plus-2tb',
    name: 'iCloud+ 2TB',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'icloud',
    url: 'https://www.apple.com/icloud',
  },
  {
    id: 'dropbox-plus',
    name: 'Dropbox Plus',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'dropbox',
    url: 'https://www.dropbox.com',
  },
  {
    id: 'dropbox-professional',
    name: 'Dropbox Professional',
    defaultPrice: 2499,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'dropbox',
    url: 'https://www.dropbox.com',
  },
  {
    id: 'notion-plus',
    name: 'Notion Plus',
    defaultPrice: 1000,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'notion',
    url: 'https://www.notion.so',
  },
  {
    id: 'evernote-personal',
    name: 'Evernote Personal',
    defaultPrice: 1499,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'evernote',
    url: 'https://evernote.com',
  },
  {
    id: 'todoist-pro',
    name: 'Todoist Pro',
    defaultPrice: 499,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'todoist',
    url: 'https://todoist.com',
  },
  {
    id: 'linear',
    name: 'Linear Standard',
    defaultPrice: 800,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'linear',
    url: 'https://linear.app',
  },
  {
    id: 'slack-pro',
    name: 'Slack Pro',
    defaultPrice: 875,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'slack',
    url: 'https://slack.com',
  },
  {
    id: 'zoom-workplace',
    name: 'Zoom Workplace',
    defaultPrice: 1399,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'zoom',
    url: 'https://zoom.us',
  },
  {
    id: 'figma-professional',
    name: 'Figma Professional',
    defaultPrice: 1500,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'figma',
    url: 'https://www.figma.com',
  },
  {
    id: 'canva-pro',
    name: 'Canva Pro',
    defaultPrice: 1500,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'canva',
    url: 'https://www.canva.com',
  },
  {
    id: 'adobe-creative-cloud',
    name: 'Adobe Creative Cloud All Apps',
    defaultPrice: 5999,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'adobe-cc',
    url: 'https://www.adobe.com/creativecloud',
  },
  {
    id: 'adobe-photography',
    name: 'Adobe Photography Plan',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'adobe-cc',
    url: 'https://www.adobe.com/creativecloud/photography',
  },
  {
    id: 'adobe-acrobat-pro',
    name: 'Adobe Acrobat Pro',
    defaultPrice: 2299,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'adobe-acrobat',
    url: 'https://www.adobe.com/acrobat',
  },
  {
    id: 'grammarly-premium',
    name: 'Grammarly Premium',
    defaultPrice: 1200,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'grammarly',
    url: 'https://www.grammarly.com',
  },
  {
    id: '1password',
    name: '1Password',
    defaultPrice: 399,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: '1password',
    url: 'https://1password.com',
  },
  {
    id: '1password-family',
    name: '1Password Families',
    defaultPrice: 699,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: '1password',
    url: 'https://1password.com',
  },
  {
    id: 'lastpass-premium',
    name: 'LastPass Premium',
    defaultPrice: 300,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'lastpass',
    url: 'https://www.lastpass.com',
  },
  {
    id: 'bitwarden-premium',
    name: 'Bitwarden Premium',
    defaultPrice: 1000,
    billingCycle: 'annual',
    category: 'productivity',
    iconKey: 'bitwarden',
    url: 'https://bitwarden.com',
  },
  {
    id: 'dashlane-premium',
    name: 'Dashlane Premium',
    defaultPrice: 5328,
    billingCycle: 'annual',
    category: 'productivity',
    iconKey: 'dashlane',
    url: 'https://www.dashlane.com',
  },
  {
    id: 'tailscale-personal-pro',
    name: 'Tailscale Personal Pro',
    defaultPrice: 600,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'tailscale',
    url: 'https://tailscale.com',
  },
  {
    id: 'superhuman',
    name: 'Superhuman',
    defaultPrice: 3000,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'superhuman',
    url: 'https://superhuman.com',
  },
  {
    id: 'raycast-pro',
    name: 'Raycast Pro',
    defaultPrice: 800,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'raycast',
    url: 'https://www.raycast.com',
  },
  {
    id: 'setapp',
    name: 'Setapp',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'setapp',
    url: 'https://setapp.com',
  },
  {
    id: 'zapier-starter',
    name: 'Zapier Starter',
    defaultPrice: 1999,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'zapier',
    url: 'https://zapier.com',
  },
  {
    id: 'trello-standard',
    name: 'Trello Standard',
    defaultPrice: 500,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'trello',
    url: 'https://trello.com',
  },
  {
    id: 'asana-starter',
    name: 'Asana Starter',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'asana',
    url: 'https://asana.com',
  },
  {
    id: 'monday-standard',
    name: 'monday.com Standard',
    defaultPrice: 1200,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'monday',
    url: 'https://monday.com',
  },
  {
    id: 'miro-starter',
    name: 'Miro Starter',
    defaultPrice: 800,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'miro',
    url: 'https://miro.com',
  },
  {
    id: 'obsidian-sync',
    name: 'Obsidian Sync',
    defaultPrice: 800,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'obsidian',
    url: 'https://obsidian.md',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // HEALTH (22 entries)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'peloton-app',
    name: 'Peloton App',
    defaultPrice: 1399,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'peloton',
    url: 'https://www.onepeloton.com',
  },
  {
    id: 'peloton-all-access',
    name: 'Peloton All-Access',
    defaultPrice: 4400,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'peloton',
    url: 'https://www.onepeloton.com',
  },
  {
    id: 'apple-fitness-plus',
    name: 'Apple Fitness+',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'apple-fitness',
    url: 'https://www.apple.com/apple-fitness-plus',
  },
  {
    id: 'strava-premium',
    name: 'Strava Premium',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'strava',
    url: 'https://www.strava.com',
  },
  {
    id: 'myfitnesspal-premium',
    name: 'MyFitnessPal Premium',
    defaultPrice: 1999,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'myfitnesspal',
    url: 'https://www.myfitnesspal.com',
  },
  {
    id: 'noom',
    name: 'Noom',
    defaultPrice: 7000,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'noom',
    url: 'https://www.noom.com',
  },
  {
    id: 'headspace',
    name: 'Headspace',
    defaultPrice: 1299,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'headspace',
    url: 'https://www.headspace.com',
  },
  {
    id: 'calm',
    name: 'Calm Premium',
    defaultPrice: 6999,
    billingCycle: 'annual',
    category: 'health',
    iconKey: 'calm',
    url: 'https://www.calm.com',
  },
  {
    id: 'whoop',
    name: 'WHOOP Membership',
    defaultPrice: 3000,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'whoop',
    url: 'https://www.whoop.com',
  },
  {
    id: 'oura-membership',
    name: 'Oura Membership',
    defaultPrice: 599,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'oura',
    url: 'https://ouraring.com',
  },
  {
    id: 'fitbit-premium',
    name: 'Fitbit Premium',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'fitbit',
    url: 'https://www.fitbit.com/global/us/technology/premium',
  },
  {
    id: 'nike-training-club',
    name: 'Nike Training Club',
    defaultPrice: 1499,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'nike',
    url: 'https://www.nike.com/ntc-app',
  },
  {
    id: 'eight-sleep',
    name: 'Eight Sleep Autopilot',
    defaultPrice: 1900,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'eight-sleep',
    url: 'https://www.eightsleep.com',
  },
  {
    id: 'betterhelp',
    name: 'BetterHelp',
    defaultPrice: 28000,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'betterhelp',
    url: 'https://www.betterhelp.com',
  },
  {
    id: 'talkiatry',
    name: 'Talkiatry',
    defaultPrice: 25000,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'talkiatry',
    url: 'https://www.talkiatry.com',
  },
  {
    id: 'cerebral',
    name: 'Cerebral',
    defaultPrice: 9900,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'cerebral',
    url: 'https://cerebral.com',
  },
  {
    id: 'nurx',
    name: 'Nurx',
    defaultPrice: 1500,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'nurx',
    url: 'https://www.nurx.com',
  },
  {
    id: 'hims',
    name: 'Hims',
    defaultPrice: 3000,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'hims',
    url: 'https://www.hims.com',
  },
  {
    id: 'hers',
    name: 'Hers',
    defaultPrice: 3000,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'hers',
    url: 'https://www.forhers.com',
  },
  {
    id: 'macrofactor',
    name: 'MacroFactor',
    defaultPrice: 7199,
    billingCycle: 'annual',
    category: 'health',
    iconKey: 'macrofactor',
    url: 'https://macrofactorapp.com',
  },
  {
    id: 'sleep-cycle-premium',
    name: 'Sleep Cycle Premium',
    defaultPrice: 3999,
    billingCycle: 'annual',
    category: 'health',
    iconKey: 'sleep-cycle',
    url: 'https://www.sleepcycle.com',
  },
  {
    id: 'traineroize',
    name: 'TrainerRoad',
    defaultPrice: 2499,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'trainerroad',
    url: 'https://www.trainerroad.com',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SHOPPING (16 entries)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'amazon-prime',
    name: 'Amazon Prime',
    defaultPrice: 14999,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'amazon',
    url: 'https://www.amazon.com/prime',
  },
  {
    id: 'amazon-prime-monthly',
    name: 'Amazon Prime (Monthly)',
    defaultPrice: 1499,
    billingCycle: 'monthly',
    category: 'shopping',
    iconKey: 'amazon',
    url: 'https://www.amazon.com/prime',
  },
  {
    id: 'costco-executive',
    name: 'Costco Executive Membership',
    defaultPrice: 13000,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'costco',
    url: 'https://www.costco.com',
  },
  {
    id: 'costco-gold-star',
    name: 'Costco Gold Star Membership',
    defaultPrice: 6500,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'costco',
    url: 'https://www.costco.com',
  },
  {
    id: 'walmart-plus',
    name: 'Walmart+',
    defaultPrice: 9800,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'walmart',
    url: 'https://www.walmart.com/plus',
  },
  {
    id: 'sams-club',
    name: "Sam's Club Membership",
    defaultPrice: 5000,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'sams-club',
    url: 'https://www.samsclub.com',
  },
  {
    id: 'sams-club-plus',
    name: "Sam's Club Plus Membership",
    defaultPrice: 11000,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'sams-club',
    url: 'https://www.samsclub.com',
  },
  {
    id: 'instacart-plus',
    name: 'Instacart+',
    defaultPrice: 9900,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'instacart',
    url: 'https://www.instacart.com',
  },
  {
    id: 'doordash-dashpass',
    name: 'DoorDash DashPass',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'shopping',
    iconKey: 'doordash',
    url: 'https://www.doordash.com/dashpass',
  },
  {
    id: 'uber-one',
    name: 'Uber One',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'shopping',
    iconKey: 'uber',
    url: 'https://www.uber.com/one',
  },
  {
    id: 'grubhub-plus',
    name: 'Grubhub+',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'shopping',
    iconKey: 'grubhub',
    url: 'https://www.grubhub.com',
  },
  {
    id: 'shipt',
    name: 'Shipt Membership',
    defaultPrice: 9900,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'shipt',
    url: 'https://www.shipt.com',
  },
  {
    id: 'thrive-market',
    name: 'Thrive Market',
    defaultPrice: 5995,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'thrive-market',
    url: 'https://thrivemarket.com',
  },
  {
    id: 'stitch-fix',
    name: 'Stitch Fix',
    defaultPrice: 2000,
    billingCycle: 'monthly',
    category: 'shopping',
    iconKey: 'stitch-fix',
    url: 'https://www.stitchfix.com',
  },
  {
    id: 'rent-the-runway',
    name: 'Rent the Runway',
    defaultPrice: 10000,
    billingCycle: 'monthly',
    category: 'shopping',
    iconKey: 'rent-the-runway',
    url: 'https://www.renttherunway.com',
  },
  {
    id: 'aaa-membership',
    name: 'AAA Plus Membership',
    defaultPrice: 12400,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'aaa',
    url: 'https://www.aaa.com',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // NEWS (22 entries)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'nyt-all-access',
    name: 'New York Times All Access',
    defaultPrice: 2500,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'nyt',
    url: 'https://www.nytimes.com',
  },
  {
    id: 'nyt-news',
    name: 'New York Times News',
    defaultPrice: 1700,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'nyt',
    url: 'https://www.nytimes.com',
  },
  {
    id: 'washington-post',
    name: 'Washington Post',
    defaultPrice: 1000,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'wapo',
    url: 'https://www.washingtonpost.com',
  },
  {
    id: 'wsj',
    name: 'Wall Street Journal',
    defaultPrice: 3999,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'wsj',
    url: 'https://www.wsj.com',
  },
  {
    id: 'economist',
    name: 'The Economist',
    defaultPrice: 2900,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'economist',
    url: 'https://www.economist.com',
  },
  {
    id: 'atlantic',
    name: 'The Atlantic',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'atlantic',
    url: 'https://www.theatlantic.com',
  },
  {
    id: 'bloomberg',
    name: 'Bloomberg',
    defaultPrice: 3499,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'bloomberg',
    url: 'https://www.bloomberg.com',
  },
  {
    id: 'financial-times',
    name: 'Financial Times',
    defaultPrice: 3900,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'ft',
    url: 'https://www.ft.com',
  },
  {
    id: 'new-yorker',
    name: 'The New Yorker',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'new-yorker',
    url: 'https://www.newyorker.com',
  },
  {
    id: 'wired',
    name: 'WIRED',
    defaultPrice: 500,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'wired',
    url: 'https://www.wired.com',
  },
  {
    id: 'la-times',
    name: 'Los Angeles Times',
    defaultPrice: 1600,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'la-times',
    url: 'https://www.latimes.com',
  },
  {
    id: 'medium',
    name: 'Medium Membership',
    defaultPrice: 500,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'medium',
    url: 'https://medium.com',
  },
  {
    id: 'substack-pro',
    name: 'Substack (Avg. Paid)',
    defaultPrice: 1000,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'substack',
    url: 'https://substack.com',
  },
  {
    id: 'apple-news-plus',
    name: 'Apple News+',
    defaultPrice: 1299,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'apple-news',
    url: 'https://www.apple.com/apple-news',
  },
  {
    id: 'the-information',
    name: 'The Information',
    defaultPrice: 39900,
    billingCycle: 'annual',
    category: 'news',
    iconKey: 'the-information',
    url: 'https://www.theinformation.com',
  },
  {
    id: 'stratechery',
    name: 'Stratechery',
    defaultPrice: 1500,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'stratechery',
    url: 'https://stratechery.com',
  },
  {
    id: 'barrons',
    name: "Barron's",
    defaultPrice: 1999,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'barrons',
    url: 'https://www.barrons.com',
  },
  {
    id: 'reuters',
    name: 'Reuters',
    defaultPrice: 3500,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'reuters',
    url: 'https://www.reuters.com',
  },
  {
    id: 'guardian-supporter',
    name: 'The Guardian Supporter',
    defaultPrice: 1300,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'guardian',
    url: 'https://www.theguardian.com',
  },
  {
    id: 'ars-technica-plus',
    name: 'Ars Technica+',
    defaultPrice: 350,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'ars-technica',
    url: 'https://arstechnica.com',
  },
  {
    id: 'the-verge-plus',
    name: 'The Verge (Subscriber)',
    defaultPrice: 700,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'the-verge',
    url: 'https://www.theverge.com',
  },
  {
    id: 'axios-pro',
    name: 'Axios Pro',
    defaultPrice: 5999,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'axios',
    url: 'https://www.axios.com/pro',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // FINANCE (16 entries)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'ynab',
    name: 'YNAB (You Need A Budget)',
    defaultPrice: 10900,
    billingCycle: 'annual',
    category: 'finance',
    iconKey: 'ynab',
    url: 'https://www.ynab.com',
  },
  {
    id: 'copilot-money',
    name: 'Copilot Money',
    defaultPrice: 1499,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'copilot-money',
    url: 'https://copilot.money',
  },
  {
    id: 'monarch-money',
    name: 'Monarch Money',
    defaultPrice: 1499,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'monarch',
    url: 'https://www.monarchmoney.com',
  },
  {
    id: 'quicken-simplifi',
    name: 'Quicken Simplifi',
    defaultPrice: 4799,
    billingCycle: 'annual',
    category: 'finance',
    iconKey: 'quicken',
    url: 'https://www.quicken.com/simplifi',
  },
  {
    id: 'quicken-classic',
    name: 'Quicken Classic',
    defaultPrice: 8388,
    billingCycle: 'annual',
    category: 'finance',
    iconKey: 'quicken',
    url: 'https://www.quicken.com',
  },
  {
    id: 'turbotax-plus',
    name: 'TurboTax Live Assisted',
    defaultPrice: 11900,
    billingCycle: 'annual',
    category: 'finance',
    iconKey: 'turbotax',
    url: 'https://turbotax.intuit.com',
  },
  {
    id: 'credit-karma-plus',
    name: 'Credit Karma Money',
    defaultPrice: 0,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'credit-karma',
    url: 'https://www.creditkarma.com',
  },
  {
    id: 'personal-capital',
    name: 'Empower Personal Dashboard',
    defaultPrice: 0,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'empower',
    url: 'https://www.empower.com',
  },
  {
    id: 'robinhood-gold',
    name: 'Robinhood Gold',
    defaultPrice: 500,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'robinhood',
    url: 'https://robinhood.com/gold',
  },
  {
    id: 'wealthfront',
    name: 'Wealthfront',
    defaultPrice: 0,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'wealthfront',
    url: 'https://www.wealthfront.com',
  },
  {
    id: 'betterment-premium',
    name: 'Betterment Premium',
    defaultPrice: 0,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'betterment',
    url: 'https://www.betterment.com',
  },
  {
    id: 'coinbase-one',
    name: 'Coinbase One',
    defaultPrice: 2999,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'coinbase',
    url: 'https://www.coinbase.com/one',
  },
  {
    id: 'morningstar-premium',
    name: 'Morningstar Investor',
    defaultPrice: 3499,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'morningstar',
    url: 'https://www.morningstar.com',
  },
  {
    id: 'seeking-alpha-premium',
    name: 'Seeking Alpha Premium',
    defaultPrice: 23900,
    billingCycle: 'annual',
    category: 'finance',
    iconKey: 'seeking-alpha',
    url: 'https://seekingalpha.com',
  },
  {
    id: 'motley-fool-stock-advisor',
    name: 'Motley Fool Stock Advisor',
    defaultPrice: 19900,
    billingCycle: 'annual',
    category: 'finance',
    iconKey: 'motley-fool',
    url: 'https://www.fool.com',
  },
  {
    id: 'acorns',
    name: 'Acorns Personal',
    defaultPrice: 300,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'acorns',
    url: 'https://www.acorns.com',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // UTILITIES (16 entries)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'nordvpn',
    name: 'NordVPN',
    defaultPrice: 1299,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'nordvpn',
    url: 'https://nordvpn.com',
  },
  {
    id: 'expressvpn',
    name: 'ExpressVPN',
    defaultPrice: 1299,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'expressvpn',
    url: 'https://www.expressvpn.com',
  },
  {
    id: 'surfshark',
    name: 'Surfshark',
    defaultPrice: 1599,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'surfshark',
    url: 'https://surfshark.com',
  },
  {
    id: 'protonvpn-plus',
    name: 'ProtonVPN Plus',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'protonvpn',
    url: 'https://protonvpn.com',
  },
  {
    id: 'proton-mail-plus',
    name: 'Proton Mail Plus',
    defaultPrice: 499,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'proton-mail',
    url: 'https://proton.me/mail',
  },
  {
    id: 'proton-unlimited',
    name: 'Proton Unlimited',
    defaultPrice: 1299,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'proton',
    url: 'https://proton.me',
  },
  {
    id: 'mullvad-vpn',
    name: 'Mullvad VPN',
    defaultPrice: 500,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'mullvad',
    url: 'https://mullvad.net',
  },
  {
    id: 'backblaze',
    name: 'Backblaze Personal Backup',
    defaultPrice: 900,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'backblaze',
    url: 'https://www.backblaze.com',
  },
  {
    id: 'carbonite',
    name: 'Carbonite Safe Basic',
    defaultPrice: 7500,
    billingCycle: 'annual',
    category: 'utilities',
    iconKey: 'carbonite',
    url: 'https://www.carbonite.com',
  },
  {
    id: 'idrive',
    name: 'IDrive 5TB',
    defaultPrice: 7995,
    billingCycle: 'annual',
    category: 'utilities',
    iconKey: 'idrive',
    url: 'https://www.idrive.com',
  },
  {
    id: 'norton-360',
    name: 'Norton 360 Standard',
    defaultPrice: 8999,
    billingCycle: 'annual',
    category: 'utilities',
    iconKey: 'norton',
    url: 'https://us.norton.com',
  },
  {
    id: 'malwarebytes-premium',
    name: 'Malwarebytes Premium',
    defaultPrice: 4499,
    billingCycle: 'annual',
    category: 'utilities',
    iconKey: 'malwarebytes',
    url: 'https://www.malwarebytes.com',
  },
  {
    id: 'cleanmymac',
    name: 'CleanMyMac X',
    defaultPrice: 3995,
    billingCycle: 'annual',
    category: 'utilities',
    iconKey: 'cleanmymac',
    url: 'https://macpaw.com/cleanmymac',
  },
  {
    id: 'lifelock-standard',
    name: 'LifeLock Standard',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'lifelock',
    url: 'https://www.lifelock.com',
  },
  {
    id: 'aura-identity',
    name: 'Aura Identity Protection',
    defaultPrice: 1200,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'aura',
    url: 'https://www.aura.com',
  },
  {
    id: 'deleteme',
    name: 'DeleteMe',
    defaultPrice: 12900,
    billingCycle: 'annual',
    category: 'utilities',
    iconKey: 'deleteme',
    url: 'https://joindeleteme.com',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OTHER (26 entries)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'duolingo-plus',
    name: 'Duolingo Super',
    defaultPrice: 1299,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'duolingo',
    url: 'https://www.duolingo.com',
  },
  {
    id: 'babbel',
    name: 'Babbel',
    defaultPrice: 1499,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'babbel',
    url: 'https://www.babbel.com',
  },
  {
    id: 'rosetta-stone',
    name: 'Rosetta Stone',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'rosetta-stone',
    url: 'https://www.rosettastone.com',
  },
  {
    id: 'masterclass',
    name: 'MasterClass Standard',
    defaultPrice: 1000,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'masterclass',
    url: 'https://www.masterclass.com',
  },
  {
    id: 'skillshare-premium',
    name: 'Skillshare Premium',
    defaultPrice: 1400,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'skillshare',
    url: 'https://www.skillshare.com',
  },
  {
    id: 'curiosity-stream',
    name: 'CuriosityStream',
    defaultPrice: 499,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'curiosity-stream',
    url: 'https://curiositystream.com',
  },
  {
    id: 'coursera-plus',
    name: 'Coursera Plus',
    defaultPrice: 5900,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'coursera',
    url: 'https://www.coursera.org',
  },
  {
    id: 'linkedin-learning',
    name: 'LinkedIn Learning',
    defaultPrice: 2999,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'linkedin',
    url: 'https://www.linkedin.com/learning',
  },
  {
    id: 'linkedin-premium',
    name: 'LinkedIn Premium Career',
    defaultPrice: 2999,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'linkedin',
    url: 'https://www.linkedin.com/premium',
  },
  {
    id: 'bumble-premium',
    name: 'Bumble Premium',
    defaultPrice: 3999,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'bumble',
    url: 'https://bumble.com',
  },
  {
    id: 'tinder-plus',
    name: 'Tinder+',
    defaultPrice: 1499,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'tinder',
    url: 'https://tinder.com',
  },
  {
    id: 'tinder-gold',
    name: 'Tinder Gold',
    defaultPrice: 2999,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'tinder',
    url: 'https://tinder.com',
  },
  {
    id: 'hinge-preferred',
    name: 'Hinge Preferred',
    defaultPrice: 3499,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'hinge',
    url: 'https://hinge.co',
  },
  {
    id: 'ancestry-plus',
    name: 'Ancestry+',
    defaultPrice: 2499,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'ancestry',
    url: 'https://www.ancestry.com',
  },
  {
    id: 'find-my-past',
    name: 'FindMyPast',
    defaultPrice: 2499,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'findmypast',
    url: 'https://www.findmypast.com',
  },
  {
    id: 'nextdoor',
    name: 'Nextdoor (Ad-Free)',
    defaultPrice: 499,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'nextdoor',
    url: 'https://nextdoor.com',
  },
  {
    id: 'discord-nitro',
    name: 'Discord Nitro',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'discord',
    url: 'https://discord.com/nitro',
  },
  {
    id: 'discord-nitro-basic',
    name: 'Discord Nitro Basic',
    defaultPrice: 299,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'discord',
    url: 'https://discord.com/nitro',
  },
  {
    id: 'snapchat-plus',
    name: 'Snapchat+',
    defaultPrice: 399,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'snapchat',
    url: 'https://www.snapchat.com',
  },
  {
    id: 'x-premium',
    name: 'X Premium',
    defaultPrice: 800,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'x',
    url: 'https://x.com',
  },
  {
    id: 'x-premium-plus',
    name: 'X Premium+',
    defaultPrice: 1600,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'x',
    url: 'https://x.com',
  },
  {
    id: 'reddit-premium',
    name: 'Reddit Premium',
    defaultPrice: 599,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'reddit',
    url: 'https://www.reddit.com/premium',
  },
  {
    id: 'patreon-avg',
    name: 'Patreon (Avg. Pledge)',
    defaultPrice: 1000,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'patreon',
    url: 'https://www.patreon.com',
  },
  {
    id: 'bark',
    name: 'Bark Premium (Parental)',
    defaultPrice: 1400,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'bark',
    url: 'https://www.bark.us',
  },
  {
    id: 'life360-plus',
    name: 'Life360 Plus',
    defaultPrice: 799,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'life360',
    url: 'https://www.life360.com',
  },
  {
    id: 'planet-fitness',
    name: 'Planet Fitness (Classic)',
    defaultPrice: 1500,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'planet-fitness',
    url: 'https://www.planetfitness.com',
  },
] as const;

/** Set of entry IDs commonly tracked by users, used for "popular" sorting */
const POPULAR_IDS = new Set([
  'netflix-standard',
  'spotify-premium',
  'youtube-premium',
  'disney-plus',
  'hulu',
  'hbo-max',
  'amazon-prime',
  'apple-tv-plus',
  'apple-music',
  'chatgpt-plus',
  'claude-pro',
  'icloud-plus-200gb',
  'google-one-2tb',
  'microsoft-365-personal',
  '1password',
  'doordash-dashpass',
  'adobe-creative-cloud',
  'ynab',
  'nordvpn',
  'headspace',
]);

/**
 * Returns true if the entry is considered popular.
 */
export function isPopular(entry: CatalogEntry): boolean {
  return POPULAR_IDS.has(entry.id);
}
