import type { LucideIcon } from 'lucide-react';
import {
  BookOpen,
  Wallet,
  Car,
  Shirt,
  Moon,
  Timer,
  Zap,
  Sprout,
  CheckCircle2,
  HeartPulse,
  Home,
  NotebookPen,
  Mail,
  Pill,
  Smile,
  FileText,
  Utensils,
  PawPrint,
  ChefHat,
  PartyPopper,
  Sparkles,
  CreditCard,
  Waves,
  Mountain,
  Mic,
  BookA,
  Dumbbell,
} from 'lucide-react';
import type { ModuleId } from '@mylife/module-registry';

/**
 * Maps each ModuleId to a Lucide React icon component.
 * Used in Sidebar, ModuleCard, and other hub UI that displays module icons.
 */
export const MODULE_ICON_MAP: Record<ModuleId, LucideIcon> = {
  books: BookOpen,
  budget: Wallet,
  car: Car,
  closet: Shirt,
  cycle: Moon,
  fast: Timer,
  flash: Zap,
  garden: Sprout,
  habits: CheckCircle2,
  health: HeartPulse,
  homes: Home,
  journal: NotebookPen,
  mail: Mail,
  meds: Pill,
  mood: Smile,
  notes: FileText,
  nutrition: Utensils,
  pets: PawPrint,
  recipes: ChefHat,
  rsvp: PartyPopper,
  stars: Sparkles,
  subs: CreditCard,
  surf: Waves,
  trails: Mountain,
  voice: Mic,
  words: BookA,
  workouts: Dumbbell,
};
