// ── Module Definition ────────────────────────────────────────────────
export { MARKET_MODULE } from './definition';

// ── Types & Schemas ──────────────────────────────────────────────────
export {
  ListingStatusSchema,
  PricingTypeSchema,
  ConditionSchema,
  ListingTypeSchema,
  FulfillmentTypeSchema,
  CategorySchema,
  ListingSchema,
  CreateListingInputSchema,
  ListingPhotoSchema,
  ConversationSchema,
  MessageContentTypeSchema,
  MessageEncryptionAlgorithmSchema,
  MessageSchema,
  CreateMessageInputSchema,
  ConversationRequestStatusSchema,
  DevicePlatformSchema,
  SecureKeyAlgorithmSchema,
  PostQuantumKemSchema,
  SecureDeviceSchema,
  SignedPreKeySchema,
  OneTimePreKeyKindSchema,
  OneTimePreKeySchema,
  RecipientPreKeyBundleSchema,
  PublishDeviceBundleInputSchema,
  ConversationRequestSchema,
  CreateConversationRequestInputSchema,
  EncryptedEnvelopeTypeSchema,
  SecureEnvelopeSchema,
  CreateSecureEnvelopeInputSchema,
  WatchlistItemSchema,
  ReviewSchema,
  SellerStatsSchema,
  SavedSearchSchema,
  ReportReasonSchema,
  ReportSchema,
  BlockSchema,
} from './types';
export type {
  ListingStatus,
  PricingType,
  Condition,
  ListingType,
  FulfillmentType,
  Category,
  Listing,
  CreateListingInput,
  ListingPhoto,
  Conversation,
  MessageContentType,
  MessageEncryptionAlgorithm,
  Message,
  CreateMessageInput,
  ConversationRequestStatus,
  DevicePlatform,
  SecureKeyAlgorithm,
  PostQuantumKem,
  SecureDevice,
  SignedPreKey,
  OneTimePreKeyKind,
  OneTimePreKey,
  RecipientPreKeyBundle,
  PublishDeviceBundleInput,
  ConversationRequest,
  CreateConversationRequestInput,
  EncryptedEnvelopeType,
  SecureEnvelope,
  CreateSecureEnvelopeInput,
  WatchlistItem,
  Review,
  SellerStats,
  SavedSearch,
  ReportReason,
  Report,
  Block,
} from './types';

// ── SQLite Cache Schema ──────────────────────────────────────────────
export { CACHE_TABLES, CACHE_INDEXES } from './db/schema';

// ── Local CRUD (SQLite cache) ────────────────────────────────────────
export type { DatabaseAdapter } from './db/crud';
export {
  getCachedCategories,
  upsertCachedCategory,
  getCachedListings,
  getCachedListingById,
  upsertCachedListing,
  deleteCachedListing,
  getCachedWatchlist,
  upsertCachedWatchlistItem,
  deleteCachedWatchlistItem,
  getCachedConversations,
  getCachedMessages,
  upsertCachedConversation,
  upsertCachedMessage,
} from './db/crud';

// ── Cloud Client (Supabase) ──────────────────────────────────────────
export {
  cloudGetCategories,
  cloudGetListings,
  cloudGetListingById,
  cloudCreateListing,
  cloudUpdateListingStatus,
  cloudSearchListings,
  cloudGetListingsWithinRadius,
  cloudGetConversations,
  cloudStartConversation,
  cloudCreateConversationRequest,
  cloudRespondToConversationRequest,
  cloudRegisterSecureDevice,
  cloudGetRecipientPreKeyBundles,
  cloudGetMessages,
  cloudSendMessage,
  cloudGetSecureEnvelopes,
  cloudSendSecureEnvelope,
  cloudGetWatchlist,
  cloudToggleWatch,
  cloudGetSellerReviews,
  cloudGetSellerStats,
  cloudGetSavedSearches,
} from './cloud/client';

// ── Encryption Helpers ───────────────────────────────────────────────
export {
  encryptMarketMessageBody,
  decryptMarketMessageBody,
} from './encryption';
