export { PETS_MODULE } from './definition';

export type {
  PetSpecies,
  PetSex,
  VetVisitType,
  MedicationFrequency,
  MedicationLogStatus,
  ExpenseCategory,
  ReminderStatus,
  WeightTrendDirection,
  Pet,
  VetVisit,
  Vaccination,
  Medication,
  MedicationLog,
  WeightEntry,
  FeedingSchedule,
  PetExpense,
  CreatePetInput,
  UpdatePetInput,
  CreateVetVisitInput,
  CreateVaccinationInput,
  CreateMedicationInput,
  RecordMedicationLogInput,
  CreateWeightEntryInput,
  CreateFeedingScheduleInput,
  CreatePetExpenseInput,
  PetListFilter,
  VaccinationReminder,
  WeightTrend,
  PetDashboard,
} from './types';

export {
  PetSpeciesSchema,
  PetSexSchema,
  VetVisitTypeSchema,
  MedicationFrequencySchema,
  MedicationLogStatusSchema,
  ExpenseCategorySchema,
  ReminderStatusSchema,
  WeightTrendDirectionSchema,
  PetSchema,
  VetVisitSchema,
  VaccinationSchema,
  MedicationSchema,
  MedicationLogSchema,
  WeightEntrySchema,
  FeedingScheduleSchema,
  PetExpenseSchema,
  CreatePetInputSchema,
  UpdatePetInputSchema,
  CreateVetVisitInputSchema,
  CreateVaccinationInputSchema,
  CreateMedicationInputSchema,
  RecordMedicationLogInputSchema,
  CreateWeightEntryInputSchema,
  CreateFeedingScheduleInputSchema,
  CreatePetExpenseInputSchema,
  PetListFilterSchema,
  VaccinationReminderSchema,
  WeightTrendSchema,
  PetDashboardSchema,
  CORE_VACCINE_SCHEDULES,
} from './types';

export {
  createPet,
  getPetById,
  listPets,
  updatePet,
  deletePet,
  createVetVisit,
  listVetVisitsForPet,
  createVaccination,
  listVaccinationsForPet,
  listDueVaccinationReminders,
  createMedication,
  getMedicationById,
  listMedicationsForPet,
  listDueMedications,
  recordMedicationLog,
  listMedicationLogs,
  createWeightEntry,
  listWeightEntriesForPet,
  createFeedingSchedule,
  listFeedingSchedulesForPet,
  createPetExpense,
  listExpensesForPet,
  getPetDashboard,
} from './db';

export {
  getReminderStatus,
  computeNextMedicationDueAt,
  collectVaccinationReminders,
  collectMedicationReminders,
} from './engine/reminders';
export type { MedicationReminder } from './engine/reminders';

export {
  calculatePetAgeYears,
  calculateWeightTrend,
  calculateOwnershipCost,
  calculateAverageMonthlyCost,
} from './engine/weight';
