export { PETS_MODULE } from './definition';

export type {
  PetSpecies,
  PetSex,
  VetVisitType,
  MedicationFrequency,
  MedicationLogStatus,
  ExpenseCategory,
  ReminderStatus,
  WeightTrendDirection,
  ExerciseActivityType,
  GroomingType,
  TrainingLocation,
  PetTimelineKind,
  BreedAlertSeverity,
  Pet,
  VetVisit,
  Vaccination,
  Medication,
  MedicationLog,
  WeightEntry,
  FeedingSchedule,
  PetExpense,
  EmergencyContact,
  ExerciseLog,
  GroomingRecord,
  TrainingLog,
  PetPhoto,
  CreatePetInput,
  UpdatePetInput,
  CreateVetVisitInput,
  CreateVaccinationInput,
  CreateMedicationInput,
  RecordMedicationLogInput,
  CreateWeightEntryInput,
  CreateFeedingScheduleInput,
  CreatePetExpenseInput,
  CreateEmergencyContactInput,
  CreateExerciseLogInput,
  CreateGroomingRecordInput,
  CreateTrainingLogInput,
  CreatePetPhotoInput,
  PetListFilter,
  VaccinationReminder,
  GroomingReminder,
  WeightTrend,
  PetDashboard,
  PetTimelineItem,
  BreedHealthAlert,
  PetSitterCard,
  PetExportBundle,
} from './types';

export {
  PetSpeciesSchema,
  PetSexSchema,
  VetVisitTypeSchema,
  MedicationFrequencySchema,
  MedicationLogStatusSchema,
  ExpenseCategorySchema,
  ReminderStatusSchema,
  WeightTrendDirectionSchema,
  ExerciseActivityTypeSchema,
  GroomingTypeSchema,
  TrainingLocationSchema,
  PetTimelineKindSchema,
  BreedAlertSeveritySchema,
  PetSchema,
  VetVisitSchema,
  VaccinationSchema,
  MedicationSchema,
  MedicationLogSchema,
  WeightEntrySchema,
  FeedingScheduleSchema,
  PetExpenseSchema,
  EmergencyContactSchema,
  ExerciseLogSchema,
  GroomingRecordSchema,
  TrainingLogSchema,
  PetPhotoSchema,
  CreatePetInputSchema,
  UpdatePetInputSchema,
  CreateVetVisitInputSchema,
  CreateVaccinationInputSchema,
  CreateMedicationInputSchema,
  RecordMedicationLogInputSchema,
  CreateWeightEntryInputSchema,
  CreateFeedingScheduleInputSchema,
  CreatePetExpenseInputSchema,
  CreateEmergencyContactInputSchema,
  CreateExerciseLogInputSchema,
  CreateGroomingRecordInputSchema,
  CreateTrainingLogInputSchema,
  CreatePetPhotoInputSchema,
  PetListFilterSchema,
  VaccinationReminderSchema,
  GroomingReminderSchema,
  WeightTrendSchema,
  PetDashboardSchema,
  PetTimelineItemSchema,
  BreedHealthAlertSchema,
  CORE_VACCINE_SCHEDULES,
} from './types';

export {
  createPet,
  getPetById,
  listPets,
  updatePet,
  deletePet,
  createVetVisit,
  listVetVisitsForPet,
  createVaccination,
  listVaccinationsForPet,
  listDueVaccinationReminders,
  createMedication,
  getMedicationById,
  listMedicationsForPet,
  listDueMedications,
  recordMedicationLog,
  listMedicationLogs,
  createWeightEntry,
  listWeightEntriesForPet,
  createFeedingSchedule,
  listFeedingSchedulesForPet,
  createPetExpense,
  listExpensesForPet,
  createEmergencyContact,
  listEmergencyContacts,
  createExerciseLog,
  listExerciseLogsForPet,
  createGroomingRecord,
  listGroomingRecordsForPet,
  listDueGroomingReminders,
  createTrainingLog,
  listTrainingLogsForPet,
  createPetPhoto,
  listPetPhotosForPet,
  getPetHealthTimeline,
  buildPetSitterCard,
  exportPetData,
  getPetDashboard,
} from './db';

export {
  getReminderStatus,
  computeNextMedicationDueAt,
  collectVaccinationReminders,
  collectMedicationReminders,
} from './engine/reminders';
export type { MedicationReminder } from './engine/reminders';

export {
  calculatePetAgeYears,
  calculateWeightTrend,
  calculateOwnershipCost,
  calculateAverageMonthlyCost,
} from './engine/weight';
export { getBreedHealthAlerts } from './engine/alerts';
export {
  formatPetSitterCard,
  serializePetExportBundle,
  serializePetExportCsvSections,
} from './engine/export';
