import type { ModuleId, ModuleDefinition } from './types';

/** All known module IDs as a readonly array, useful for iteration. */
export const MODULE_IDS: readonly ModuleId[] = [
  'books',
  'budget',
  'car',
  'closet',
  'cycle',
  'fast',
  'flash',
  'forums',
  'garden',
  'habits',
  'health',
  'homes',
  'journal',
  'mail',
  'market',
  'meds',
  'mood',
  'notes',
  'nutrition',
  'pets',
  'recipes',
  'rsvp',
  'stars',
  'subs',
  'surf',
  'trails',
  'voice',
  'words',
  'workouts',
] as const;

/** Modules included in the free tier (no purchase required). */
export const FREE_MODULES: readonly ModuleId[] = [
  'fast',
  'forums',
  'journal',
  'market',
  'mood',
  'notes',
  'voice',
] as const;

/**
 * Complete metadata for every module in the MyLife suite.
 *
 * Each entry provides enough information for the hub app to render
 * module cards, navigation tabs, and onboarding flows without
 * loading the module's actual code.
 */
export const MODULE_METADATA: Record<ModuleId, ModuleDefinition> = {
  books: {
    id: 'books',
    name: 'MyBooks',
    tagline: 'Track your reading life',
    icon: '\u{1F4DA}',
    accentColor: '#C9894D',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'bk_',
    navigation: {
      tabs: [
        { key: 'home', label: 'Home', icon: 'home' },
        { key: 'library', label: 'Library', icon: 'book' },
        { key: 'search', label: 'Search', icon: 'search' },
        { key: 'stats', label: 'Stats', icon: 'bar-chart' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'book-detail', title: 'Book Details' },
        { name: 'add-book', title: 'Add Book' },
        { name: 'edit-review', title: 'Edit Review' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  budget: {
    id: 'budget',
    name: 'MyBudget',
    tagline: 'Envelope budgeting made simple',
    icon: '\u{1F4B0}',
    accentColor: '#22C55E',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'bg_',
    navigation: {
      tabs: [
        { key: 'budget', label: 'Budget', icon: 'wallet' },
        { key: 'transactions', label: 'Transactions', icon: 'list' },
        { key: 'subscriptions', label: 'Subscriptions', icon: 'repeat' },
        { key: 'reports', label: 'Reports', icon: 'pie-chart' },
        { key: 'accounts', label: 'Accounts', icon: 'credit-card' },
      ],
      screens: [
        { name: 'envelope-detail', title: 'Envelope' },
        { name: 'add-transaction', title: 'Add Transaction' },
        { name: 'subscription-detail', title: 'Subscription' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  fast: {
    id: 'fast',
    name: 'MyFast',
    tagline: 'Intermittent fasting timer',
    icon: '\u{23F1}\u{FE0F}',
    accentColor: '#14B8A6',
    tier: 'free',
    storageType: 'sqlite',
    tablePrefix: 'ft_',
    navigation: {
      tabs: [
        { key: 'timer', label: 'Timer', icon: 'clock' },
        { key: 'history', label: 'History', icon: 'calendar' },
        { key: 'stats', label: 'Stats', icon: 'bar-chart' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'fast-detail', title: 'Fast Details' },
        { name: 'choose-plan', title: 'Choose Plan' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  health: {
    id: 'health',
    name: 'MyHealth',
    tagline: 'Your complete health companion',
    icon: '\u{1FA7A}',
    accentColor: '#10B981',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'hl_',
    freeSections: ['fasting'],
    navigation: {
      tabs: [
        { key: 'today', label: 'Today', icon: 'activity' },
        { key: 'fasting', label: 'Fasting', icon: 'clock' },
        { key: 'vitals', label: 'Vitals', icon: 'heart' },
        { key: 'insights', label: 'Insights', icon: 'trending-up' },
        { key: 'vault', label: 'Vault', icon: 'shield' },
      ],
      screens: [
        { name: 'fast-detail', title: 'Fast Details' },
        { name: 'choose-plan', title: 'Choose Plan' },
        { name: 'med-detail', title: 'Medication' },
        { name: 'add-med', title: 'Add Medication' },
        { name: 'schedule', title: 'Schedule' },
        { name: 'interactions', title: 'Interactions' },
        { name: 'measurement-log', title: 'Log Measurement' },
        { name: 'vital-detail', title: 'Vital Detail' },
        { name: 'cycle-tracker', title: 'Cycle Tracker' },
        { name: 'sleep-detail', title: 'Sleep Detail' },
        { name: 'mood-check-in', title: 'Mood Check-In' },
        { name: 'correlation', title: 'Correlations' },
        { name: 'wellness-timeline', title: 'Wellness Timeline' },
        { name: 'export', title: 'Export Data' },
        { name: 'add-document', title: 'Add Document' },
        { name: 'document-viewer', title: 'Document' },
        { name: 'emergency-info', title: 'Emergency Info' },
        { name: 'health-sync-settings', title: 'Health Sync' },
        { name: 'goal-detail', title: 'Goal' },
        { name: 'add-goal', title: 'New Goal' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  recipes: {
    id: 'recipes',
    name: 'MyGarden',
    tagline: 'Grow it, cook it, host it',
    icon: '\u{1F331}',
    accentColor: '#22C55E',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'rc_',
    navigation: {
      tabs: [
        { key: 'home', label: 'Home', icon: 'home' },
        { key: 'recipes', label: 'Recipes', icon: 'book-open' },
        { key: 'meal-plan', label: 'Meal Planner', icon: 'calendar' },
        { key: 'garden', label: 'Garden', icon: 'leaf' },
        { key: 'events', label: 'Events', icon: 'users' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'recipe-detail', title: 'Recipe' },
        { name: 'add-recipe', title: 'Add Recipe' },
        { name: 'cooking-mode', title: 'Cooking Mode' },
        { name: 'garden-journal', title: 'Garden Journal' },
        { name: 'event-detail', title: 'Event' },
        { name: 'import-url', title: 'Import from URL' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  rsvp: {
    id: 'rsvp',
    name: 'MyRSVP',
    tagline: 'Events, invites, and RSVP tracking',
    icon: '\u{1F48C}',
    accentColor: '#FB7185',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'rv_',
    navigation: {
      tabs: [
        { key: 'events', label: 'Events', icon: 'calendar' },
        { key: 'guests', label: 'Guests', icon: 'users' },
        { key: 'polls', label: 'Polls', icon: 'bar-chart' },
        { key: 'feed', label: 'Feed', icon: 'message-circle' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'event-detail', title: 'Event Details' },
        { name: 'invite-management', title: 'Invites' },
        { name: 'check-in', title: 'Check-in' },
        { name: 'photo-album', title: 'Photo Album' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  surf: {
    id: 'surf',
    name: 'MySurf',
    tagline: 'Surf forecasts and spot intel',
    icon: '\u{1F3C4}',
    accentColor: '#3B82F6',
    tier: 'premium',
    storageType: 'sqlite',
    navigation: {
      tabs: [
        { key: 'forecast', label: 'Forecast', icon: 'cloud' },
        { key: 'map', label: 'Map', icon: 'map' },
        { key: 'spots', label: 'Spots', icon: 'map-pin' },
        { key: 'alerts', label: 'Alerts', icon: 'bell' },
        { key: 'profile', label: 'Profile', icon: 'user' },
      ],
      screens: [
        { name: 'spot-detail', title: 'Spot Details' },
        { name: 'buoy-detail', title: 'Buoy Data' },
        { name: 'session-log', title: 'Session Log' },
      ],
    },
    requiresAuth: true,
    requiresNetwork: true,
    version: '0.1.0',
  },
  workouts: {
    id: 'workouts',
    name: 'MyWorkouts',
    tagline: 'Body-map guided workouts and builder',
    icon: '\u{1F4AA}',
    accentColor: '#EF4444',
    tier: 'premium',
    storageType: 'sqlite',
    navigation: {
      tabs: [
        { key: 'home', label: 'Home', icon: 'home' },
        { key: 'explore', label: 'Explore', icon: 'search' },
        { key: 'workouts', label: 'Workouts', icon: 'layers' },
        { key: 'progress', label: 'Progress', icon: 'trending-up' },
        { key: 'profile', label: 'Profile', icon: 'user' },
      ],
      screens: [
        { name: 'workout-detail', title: 'Workout' },
        { name: 'exercise-detail', title: 'Exercise' },
        { name: 'builder', title: 'Workout Builder' },
        { name: 'recordings', title: 'Form Recordings' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.2.0',
  },
  homes: {
    id: 'homes',
    name: 'MyHomes',
    tagline: 'Real estate, reimagined',
    icon: '\u{1F3E0}',
    accentColor: '#D97706',
    tier: 'premium',
    storageType: 'sqlite',
    navigation: {
      tabs: [
        { key: 'search', label: 'Search', icon: 'search' },
        { key: 'map', label: 'Map', icon: 'map' },
        { key: 'saved', label: 'Saved', icon: 'heart' },
        { key: 'alerts', label: 'Alerts', icon: 'bell' },
        { key: 'profile', label: 'Profile', icon: 'user' },
      ],
      screens: [
        { name: 'listing-detail', title: 'Listing' },
        { name: 'agent-profile', title: 'Agent' },
        { name: 'mortgage-calc', title: 'Mortgage Calculator' },
      ],
    },
    requiresAuth: true,
    requiresNetwork: true,
    version: '0.1.0',
  },
  car: {
    id: 'car',
    name: 'MyCar',
    tagline: 'Vehicle maintenance tracker',
    icon: '\u{1F697}',
    accentColor: '#6366F1',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'cr_',
    navigation: {
      tabs: [
        { key: 'dashboard', label: 'Dashboard', icon: 'gauge' },
        { key: 'maintenance', label: 'Maintenance', icon: 'wrench' },
        { key: 'fuel', label: 'Fuel', icon: 'droplet' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'vehicle-detail', title: 'Vehicle' },
        { name: 'add-record', title: 'Add Record' },
        { name: 'service-history', title: 'Service History' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  habits: {
    id: 'habits',
    name: 'MyHabits',
    tagline: 'Build habits that stick',
    icon: '\u{2705}',
    accentColor: '#8B5CF6',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'hb_',
    navigation: {
      tabs: [
        { key: 'today', label: 'Today', icon: 'check-circle' },
        { key: 'habits', label: 'Habits', icon: 'list' },
        { key: 'stats', label: 'Stats', icon: 'bar-chart' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'habit-detail', title: 'Habit' },
        { name: 'add-habit', title: 'New Habit' },
        { name: 'streak-detail', title: 'Streak' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  meds: {
    id: 'meds',
    name: 'MyMeds',
    tagline: 'Never miss a dose',
    icon: '\u{1F48A}',
    accentColor: '#06B6D4',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'md_',
    navigation: {
      tabs: [
        { key: 'today', label: 'Today', icon: 'clock' },
        { key: 'medications', label: 'Medications', icon: 'pill' },
        { key: 'history', label: 'History', icon: 'calendar' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'med-detail', title: 'Medication' },
        { name: 'add-med', title: 'Add Medication' },
        { name: 'schedule', title: 'Schedule' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  words: {
    id: 'words',
    name: 'MyWords',
    tagline: 'Dictionary + thesaurus in 270 languages',
    icon: '\u{1F4D6}',
    accentColor: '#0EA5E9',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'wd_',
    navigation: {
      tabs: [
        { key: 'lookup', label: 'Lookup', icon: 'search' },
        { key: 'helper', label: 'Word Helper', icon: 'sparkles' },
        { key: 'languages', label: 'Languages', icon: 'globe' },
        { key: 'saved', label: 'Saved', icon: 'bookmark' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'word-detail', title: 'Word' },
        { name: 'saved-word-detail', title: 'Saved Word' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: true,
    version: '0.1.0',
  },
  closet: {
    id: 'closet',
    name: 'MyCloset',
    tagline: 'Your wardrobe, fully private',
    icon: '\u{1F457}',
    accentColor: '#E879A8',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'cl_',
    navigation: {
      tabs: [
        { key: 'wardrobe', label: 'Wardrobe', icon: 'shirt' },
        { key: 'outfits', label: 'Outfits', icon: 'layers' },
        { key: 'calendar', label: 'Calendar', icon: 'calendar' },
        { key: 'stats', label: 'Stats', icon: 'bar-chart-2' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'item-detail', title: 'Item' },
        { name: 'outfit-detail', title: 'Outfit' },
        { name: 'add-item', title: 'Add Item' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  cycle: {
    id: 'cycle',
    name: 'MyCycle',
    tagline: 'Private period and fertility tracker',
    icon: '\u{1F319}',
    accentColor: '#F472B6',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'cy_',
    navigation: {
      tabs: [
        { key: 'today', label: 'Today', icon: 'calendar-check' },
        { key: 'calendar', label: 'Calendar', icon: 'calendar' },
        { key: 'insights', label: 'Insights', icon: 'trending-up' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'log-day', title: 'Log Day' },
        { name: 'cycle-detail', title: 'Cycle Detail' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  forums: {
    id: 'forums',
    name: 'MyForums',
    tagline: 'Community discussions, your way',
    icon: '\u{1F4AC}',
    accentColor: '#F43F5E',
    tier: 'free',
    storageType: 'supabase',
    tablePrefix: 'fr_',
    navigation: {
      tabs: [
        { key: 'feed', label: 'Feed', icon: 'rss' },
        { key: 'communities', label: 'Communities', icon: 'users' },
        { key: 'search', label: 'Search', icon: 'search' },
        { key: 'saved', label: 'Saved', icon: 'bookmark' },
        { key: 'profile', label: 'Profile', icon: 'user' },
      ],
      screens: [
        { name: 'community-detail', title: 'Community' },
        { name: 'thread-detail', title: 'Thread' },
        { name: 'create-thread', title: 'New Thread' },
        { name: 'reply-thread', title: 'Reply' },
        { name: 'create-community', title: 'New Community' },
        { name: 'member-list', title: 'Members' },
        { name: 'mod-dashboard', title: 'Moderation' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: true,
    version: '0.1.0',
  },
  flash: {
    id: 'flash',
    name: 'MyFlash',
    tagline: 'Spaced repetition flashcards',
    icon: '\u{26A1}',
    accentColor: '#FBBF24',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'fl_',
    navigation: {
      tabs: [
        { key: 'study', label: 'Study', icon: 'play-circle' },
        { key: 'decks', label: 'Decks', icon: 'layers' },
        { key: 'stats', label: 'Stats', icon: 'bar-chart-2' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'deck-detail', title: 'Deck' },
        { name: 'card-editor', title: 'Edit Card' },
        { name: 'review', title: 'Review' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: true,
    version: '0.1.0',
  },
  garden: {
    id: 'garden',
    name: 'MyGarden',
    tagline: 'Plant care and garden planner',
    icon: '\u{1F331}',
    accentColor: '#22C55E',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'gd_',
    navigation: {
      tabs: [
        { key: 'garden', label: 'Garden', icon: 'flower-2' },
        { key: 'tasks', label: 'Tasks', icon: 'check-circle' },
        { key: 'journal', label: 'Journal', icon: 'book-open' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'plant-detail', title: 'Plant' },
        { name: 'add-plant', title: 'Add Plant' },
        { name: 'journal-entry', title: 'Journal Entry' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  journal: {
    id: 'journal',
    name: 'MyJournal',
    tagline: 'Private daily journal',
    icon: '\u{1F4D3}',
    accentColor: '#A78BFA',
    tier: 'free',
    storageType: 'sqlite',
    tablePrefix: 'jn_',
    navigation: {
      tabs: [
        { key: 'today', label: 'Today', icon: 'edit-3' },
        { key: 'entries', label: 'Entries', icon: 'book-open' },
        { key: 'search', label: 'Search', icon: 'search' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'entry-detail', title: 'Entry' },
        { name: 'new-entry', title: 'New Entry' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  market: {
    id: 'market',
    name: 'MyMarket',
    tagline: 'Buy, sell, and trade with your community',
    icon: '\u{1F3EA}',
    accentColor: '#E11D48',
    tier: 'free',
    storageType: 'supabase',
    tablePrefix: 'mk_',
    navigation: {
      tabs: [
        { key: 'browse', label: 'Browse', icon: 'search' },
        { key: 'sell', label: 'Sell', icon: 'plus-circle' },
        { key: 'messages', label: 'Messages', icon: 'message-circle' },
        { key: 'saved', label: 'Saved', icon: 'heart' },
        { key: 'profile', label: 'Profile', icon: 'user' },
      ],
      screens: [
        { name: 'listing-detail', title: 'Listing' },
        { name: 'create-listing', title: 'New Listing' },
        { name: 'edit-listing', title: 'Edit Listing' },
        { name: 'chat-thread', title: 'Chat' },
        { name: 'category-browser', title: 'Categories' },
        { name: 'search-results', title: 'Search' },
        { name: 'seller-profile', title: 'Seller' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  mail: {
    id: 'mail',
    name: 'MyMail',
    tagline: 'Self-hosted private email',
    icon: '\u{1F4EC}',
    accentColor: '#3B82F6',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'ml_',
    navigation: {
      tabs: [
        { key: 'inbox', label: 'Inbox', icon: 'inbox' },
        { key: 'compose', label: 'Compose', icon: 'edit' },
        { key: 'folders', label: 'Folders', icon: 'folder' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'message-detail', title: 'Message' },
        { name: 'compose-message', title: 'Compose' },
        { name: 'server-setup', title: 'Server Setup' },
      ],
    },
    requiresAuth: true,
    requiresNetwork: true,
    version: '0.1.0',
  },
  mood: {
    id: 'mood',
    name: 'MyMood',
    tagline: 'Track your emotional wellness',
    icon: '\u{1F3AD}',
    accentColor: '#FB923C',
    tier: 'free',
    storageType: 'sqlite',
    tablePrefix: 'mo_',
    navigation: {
      tabs: [
        { key: 'today', label: 'Today', icon: 'smile' },
        { key: 'history', label: 'History', icon: 'clock' },
        { key: 'insights', label: 'Insights', icon: 'trending-up' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'log-mood', title: 'Log Mood' },
        { name: 'day-detail', title: 'Day Detail' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  notes: {
    id: 'notes',
    name: 'MyNotes',
    tagline: 'Plain markdown notes, no lock-in',
    icon: '\u{1F4DD}',
    accentColor: '#64748B',
    tier: 'free',
    storageType: 'sqlite',
    tablePrefix: 'nt_',
    navigation: {
      tabs: [
        { key: 'notes', label: 'Notes', icon: 'file-text' },
        { key: 'folders', label: 'Folders', icon: 'folder' },
        { key: 'search', label: 'Search', icon: 'search' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'note-editor', title: 'Edit Note' },
        { name: 'note-preview', title: 'Preview' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  nutrition: {
    id: 'nutrition',
    name: 'MyNutrition',
    tagline: 'Track calories, macros, and 84+ nutrients',
    icon: '\u{1F957}',
    accentColor: '#F97316',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'nu_',
    navigation: {
      tabs: [
        { key: 'diary', label: 'Diary', icon: 'book-open' },
        { key: 'search', label: 'Search', icon: 'search' },
        { key: 'dashboard', label: 'Dashboard', icon: 'pie-chart' },
        { key: 'trends', label: 'Trends', icon: 'trending-up' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'food-detail', title: 'Food Details' },
        { name: 'add-food', title: 'Add Food' },
        { name: 'scan', title: 'Scan Barcode' },
        { name: 'photo', title: 'Photo Log' },
        { name: 'meal-edit', title: 'Edit Meal' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  pets: {
    id: 'pets',
    name: 'MyPets',
    tagline: 'Pet health records and care tracker',
    icon: '\u{1F43E}',
    accentColor: '#F59E0B',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'pt_',
    navigation: {
      tabs: [
        { key: 'pets', label: 'Pets', icon: 'heart' },
        { key: 'health', label: 'Health', icon: 'activity' },
        { key: 'reminders', label: 'Reminders', icon: 'bell' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'pet-detail', title: 'Pet' },
        { name: 'add-pet', title: 'Add Pet' },
        { name: 'vet-visit', title: 'Vet Visit' },
        { name: 'vaccination', title: 'Vaccination' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  stars: {
    id: 'stars',
    name: 'MyStars',
    tagline: 'Private astrology and birth charts',
    icon: '\u{2728}',
    accentColor: '#8B5CF6',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'st_',
    navigation: {
      tabs: [
        { key: 'chart', label: 'Chart', icon: 'compass' },
        { key: 'transits', label: 'Transits', icon: 'sun' },
        { key: 'compatibility', label: 'Match', icon: 'users' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'birth-chart', title: 'Birth Chart' },
        { name: 'add-profile', title: 'Add Profile' },
        { name: 'transit-detail', title: 'Transit Detail' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  subs: {
    id: 'subs',
    name: 'MySubs',
    tagline: 'Subscription cost tracker',
    icon: '\u{1F4B3}',
    accentColor: '#10B981',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'sb_',
    navigation: {
      tabs: [
        { key: 'dashboard', label: 'Dashboard', icon: 'credit-card' },
        { key: 'subscriptions', label: 'Subs', icon: 'list' },
        { key: 'calendar', label: 'Calendar', icon: 'calendar' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'sub-detail', title: 'Subscription' },
        { name: 'add-sub', title: 'Add Subscription' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  trails: {
    id: 'trails',
    name: 'MyTrails',
    tagline: 'Offline hiking and trail guide',
    icon: '\u{1F97E}',
    accentColor: '#65A30D',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'tr_',
    navigation: {
      tabs: [
        { key: 'map', label: 'Map', icon: 'map' },
        { key: 'trails', label: 'Trails', icon: 'navigation' },
        { key: 'recordings', label: 'Recordings', icon: 'activity' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'trail-detail', title: 'Trail' },
        { name: 'recording', title: 'Recording' },
        { name: 'elevation-profile', title: 'Elevation' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  voice: {
    id: 'voice',
    name: 'MyVoice',
    tagline: 'Private on-device dictation',
    icon: '\u{1F399}\u{FE0F}',
    accentColor: '#EF4444',
    tier: 'free',
    storageType: 'sqlite',
    tablePrefix: 'vc_',
    navigation: {
      tabs: [
        { key: 'dictate', label: 'Dictate', icon: 'mic' },
        { key: 'history', label: 'History', icon: 'clock' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'transcription-detail', title: 'Transcription' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
};
