// @mylife/recipes — MyGarden module

export { RECIPES_MODULE } from './definition';

export type {
  Recipe,
  CreateRecipe,
  UpdateRecipe,
  Ingredient,
  CreateIngredient,
  StructuredIngredient,
  ParsedIngredient,
  ParsedRecipe,
  RecipeTag,
  Difficulty,
  RecipeFilters,
  Step,
  CookingStepWithTimer,
  MealPlan,
  MealPlanItem,
  MealPlanWeek,
  MealSlot,
  PlantLocation,
  GardenPlant,
  GardenPlantDashboard,
  GardenJournalEntry,
  Harvest,
  PlantCareLog,
  PlantCareType,
  Event,
  EventBundle,
  EventAllergyWarning,
  EventCourse,
  EventGuest,
  EventResponse,
  EventTimelineItem,
  EventInviteBundle,
  SubstitutionSuggestion,
  PantryItem,
  CreatePantryItem,
  UpdatePantryItem,
  PantryFilters,
  GrocerySection,
  MergedGroceryItem,
  ShoppingListItem,
  ConsolidatedShoppingItem,
  MatchOptions,
  MatchedIngredient,
  RecipeMatch,
  ExpiringRecipeSuggestion,
  DeductionResult,
  StorageLocation,
  ExpirationStatus,
} from './types';
export type { ScaledIngredient } from './scaling';

export {
  createRecipe,
  getRecipes,
  getRecipeById,
  updateRecipe,
  toggleFavorite,
  setRating,
  deleteRecipe,
  countRecipes,
  addIngredient,
  getIngredients,
  getStructuredIngredients,
  updateIngredient,
  deleteIngredient,
  addTag,
  getTags,
  deleteTag,
  getSetting,
  setSetting,
} from './db/crud';
export {
  createPantryItem,
  getPantryItems,
  getPantryItemById,
  updatePantryItem,
  deletePantryItem,
  getPantryItemByBarcode,
  getExpiringItems,
  getPantryItemsByName,
  bulkUpdateQuantities,
} from './db/pantry';
export {
  addEventGuest,
  addEventMenuItem,
  addEventTimelineItem,
  addGardenJournalEntry,
  addPotluckClaim,
  createPlantCareLog,
  createEvent,
  createHostedEvent,
  createGardenPlant,
  detectStepTimerMinutes,
  generateEventShoppingList,
  getEventByInviteToken,
  getEventBundle,
  getEventInviteBundle,
  generateMealPlanShoppingList,
  getEventAllergyWarnings,
  getGardenDashboard,
  getGardenLayoutCells,
  getGardenLayouts,
  getGardenJournal,
  getGardenPlants,
  getHostedEvents,
  getCookingStepsWithTimers,
  getMealPlanWeek,
  getMealPlanWeekBundle,
  getNextWateringDate,
  getRecipesForHarvest,
  linkHarvestToRecipes,
  logHarvest,
  markPlantWatered,
  removeMealPlanItem,
  replaceEventMenuWithRecipes,
  respondToEventInvite,
  respondToInviteToken,
  respondToInvite,
  setEventMenu,
  suggestIngredientSubstitutions,
  upsertGardenLayout,
  upsertMealPlanItem,
} from './db/mygarden';
export {
  parseIngredientText,
  parseRecipeFromText,
  parseRecipeFromHtml,
  parseIsoDuration,
} from './parser';
export type { UrlParsedRecipe } from './parser';
export { scaleIngredients } from './scaling';
export {
  categorizeItem,
  mergeIngredients,
  generateShoppingList,
  UNIT_CONVERSIONS,
  areUnitsCompatible,
  convertUnit,
  bestDisplayUnit,
} from './grocery';
export {
  normalizeItemName,
  resolveItemName,
  itemsMatch,
  fuzzyItemMatch,
  classifyExpiration,
  daysUntilExpiration,
  getExpirationColor,
  getExpirationLabel,
  previewDeduction,
  deductPantryForRecipe,
  matchRecipesToPantry,
  suggestRecipesForExpiringItems,
  calculateMaxServings,
  lookupBarcode,
  mapOffCategoryToSection,
  identifyFood,
} from './pantry';
export type { OffLookupResult, OffNutritionData, FoodRecognitionResult } from './pantry';
export {
  toFraction,
  formatQuantity,
  formatDuration,
} from './utils';
