// @mylife/budget — MyBudget module

// Module definition
export { BUDGET_MODULE } from './definition';
export type { BudgetExportBundle, BudgetResetResult } from './portability';

// Types & schemas
export {
  // V1-V3
  AccountType,
  TransactionDirection,
  EnvelopeSchema,
  EnvelopeInsertSchema,
  EnvelopeUpdateSchema,
  AccountSchema,
  AccountInsertSchema,
  AccountUpdateSchema,
  BudgetTransactionSchema,
  BudgetTransactionInsertSchema,
  BudgetTransactionUpdateSchema,
  BudgetTransactionFilterSchema,
  BudgetGoalSchema,
  BudgetGoalInsertSchema,
  BudgetGoalUpdateSchema,
  BudgetSettingSchema,
  BillingCycle,
  SubscriptionStatus,
  BudgetSubscriptionSchema,
  BudgetSubscriptionInsertSchema,
  BudgetSubscriptionUpdateSchema,
  BudgetSubscriptionFilterSchema,
  CatalogCategorySchema,
  // V4 — Budget engine
  CategoryGroupSchema,
  CategoryGroupInsertSchema,
  CategoryGroupUpdateSchema,
  BudgetAllocationSchema,
  BudgetAllocationInsertSchema,
  TransactionSplitSchema,
  TransactionSplitInsertSchema,
  RecurringFrequency,
  RecurringTemplateSchema,
  RecurringTemplateInsertSchema,
  RecurringTemplateUpdateSchema,
  PayeeCacheSchema,
  AmountSign,
  CsvProfileSchema,
  CsvProfileInsertSchema,
  PriceHistorySchema,
  NotificationType,
  NotificationLogSchema,
  MatchType,
  TransactionRuleSchema,
  TransactionRuleInsertSchema,
  TransactionRuleUpdateSchema,
  NetWorthSnapshotSchema,
  PayoffStrategy,
  DebtPayoffPlanSchema,
  DebtPayoffPlanInsertSchema,
  Compounding,
  DebtPayoffDebtSchema,
  DebtPayoffDebtInsertSchema,
  BudgetRolloverSchema,
  BudgetAlertSchema,
  BudgetAlertInsertSchema,
  AlertHistorySchema,
  CurrencySchema,
  ExchangeRateSchema,
  SharingMode,
  SharedEnvelopeSchema,
} from './types';

// Bank sync contract
export * from './bank-sync';
export type {
  // V1-V3
  Envelope,
  EnvelopeInsert,
  EnvelopeUpdate,
  Account,
  AccountInsert,
  AccountUpdate,
  BudgetTransaction,
  BudgetTransactionInsert,
  BudgetTransactionUpdate,
  BudgetTransactionFilter,
  BudgetGoal,
  BudgetGoalInsert,
  BudgetGoalUpdate,
  BudgetSetting,
  BudgetSubscription,
  BudgetSubscriptionInsert,
  BudgetSubscriptionUpdate,
  BudgetSubscriptionFilter,
  CatalogEntry,
  CatalogCategory,
  // V4
  CategoryGroup,
  CategoryGroupInsert,
  CategoryGroupUpdate,
  BudgetAllocation,
  BudgetAllocationInsert,
  TransactionSplit,
  TransactionSplitInsert,
  RecurringTemplate,
  RecurringTemplateInsert,
  RecurringTemplateUpdate,
  PayeeCache,
  CsvProfile,
  CsvProfileInsert,
  PriceHistory,
  NotificationLog,
  TransactionRule,
  TransactionRuleInsert,
  TransactionRuleUpdate,
  NetWorthSnapshot,
  DebtPayoffPlan,
  DebtPayoffPlanInsert,
  DebtPayoffDebt,
  DebtPayoffDebtInsert,
  BudgetRollover,
  BudgetAlert,
  BudgetAlertInsert,
  AlertHistory,
  Currency,
  ExchangeRate,
  SharedEnvelope,
} from './types';

// Database operations
export {
  ALL_TABLES,
  BUDGET_TABLE_NAMES,
  CREATE_ENVELOPES,
  CREATE_ACCOUNTS,
  CREATE_TRANSACTIONS,
  CREATE_GOALS,
  CREATE_SETTINGS,
  CREATE_SUBSCRIPTIONS,
  CREATE_BANK_CONNECTIONS,
  CREATE_BANK_ACCOUNTS,
  CREATE_BANK_TRANSACTIONS_RAW,
  CREATE_BANK_SYNC_STATE,
  CREATE_BANK_WEBHOOK_EVENTS,
  CORE_TABLES,
  BANK_SYNC_TABLES,
  SUBSCRIPTION_TABLES,
  SUBSCRIPTION_INDEXES,
  CORE_INDEXES,
  BANK_SYNC_INDEXES,
  CREATE_INDEXES,
  SEED_SETTINGS,
  SEED_DEFAULT_ACCOUNTS,
  SEED_DEFAULT_ENVELOPES,
  // V4 schema
  V4_ALL_TABLES,
  V4_INDEXES,
  V4_ALTER_STATEMENTS,
  V4_BUDGET_ENGINE_TABLES,
  V4_RULES_GOALS_TABLES,
  V4_REPORTING_TABLES,
  CREATE_CATEGORY_GROUPS,
  CREATE_BUDGET_ALLOCATIONS,
  CREATE_TRANSACTION_SPLITS,
  CREATE_RECURRING_TEMPLATES,
  CREATE_PAYEE_CACHE,
  CREATE_CSV_PROFILES,
  CREATE_PRICE_HISTORY,
  CREATE_NOTIFICATION_LOG,
  CREATE_TRANSACTION_RULES,
  CREATE_NET_WORTH_SNAPSHOTS,
  CREATE_DEBT_PAYOFF_PLANS,
  CREATE_DEBT_PAYOFF_DEBTS,
  CREATE_BUDGET_ROLLOVERS,
  CREATE_BUDGET_ALERTS,
  CREATE_ALERT_HISTORY,
  CREATE_CURRENCIES,
  CREATE_EXCHANGE_RATES,
  CREATE_SHARED_ENVELOPES,
  // V1-V3 CRUD
  createEnvelope,
  getEnvelope,
  getEnvelopes,
  listEnvelopes,
  updateEnvelope,
  deleteEnvelope,
  createAccount,
  getAccount,
  getAccounts,
  listAccounts,
  updateAccount,
  deleteAccount,
  createTransaction,
  getTransaction,
  getTransactions,
  listTransactions,
  updateTransaction,
  deleteTransaction,
  createGoal,
  getGoalById,
  getGoals,
  updateGoal,
  deleteGoal,
  getSetting,
  setSetting,
  createSubscription,
  getSubscriptionById,
  getSubscriptions,
  updateSubscription,
  deleteSubscription,
  pauseSubscription,
  cancelSubscription,
  resumeSubscription,
  // V4 — Category Groups
  createCategoryGroup,
  getCategoryGroupById,
  getCategoryGroups,
  updateCategoryGroup,
  deleteCategoryGroup,
  getEnvelopesByGroup,
  setEnvelopeGroup,
  // V4 — Transaction Splits & Budget Helpers
  createTransactionSplits,
  getSplitsByTransaction,
  replaceSplits,
  deleteSplitsByTransaction,
  getActivityByEnvelope,
  getTotalIncome,
  // V4 — Recurring Templates
  createRecurringTemplate,
  getRecurringTemplateById,
  getRecurringTemplateBySubscriptionId,
  getActiveTemplates,
  updateRecurringTemplate,
  getDueTemplates,
  // V4 — Transaction Rules
  createTransactionRule,
  getTransactionRuleById,
  getTransactionRules,
  getEnabledTransactionRules,
  updateTransactionRule,
  deleteTransactionRule,
  // V4 — Payee Cache
  updatePayeeCache,
  getPayeeSuggestions,
  getEnvelopeSuggestion,
  // V4 — Transfers
  createTransfer,
  getTransferPair,
  // V4 — Net Worth Snapshots
  createNetWorthSnapshot,
  getNetWorthSnapshotById,
  getNetWorthSnapshotByMonth,
  getNetWorthSnapshots,
  updateNetWorthSnapshot,
  deleteNetWorthSnapshot,
  // V4 — Debt Payoff
  createDebtPayoffPlan,
  getDebtPayoffPlanById,
  getDebtPayoffPlans,
  getActiveDebtPayoffPlans,
  updateDebtPayoffPlan,
  deleteDebtPayoffPlan,
  createDebtPayoffDebt,
  getDebtPayoffDebtById,
  getDebtsByPlan,
  updateDebtPayoffDebt,
  deleteDebtPayoffDebt,
  // V4 — Budget Rollovers
  createRollover,
  getRolloverById,
  getRollovers,
  getRolloversByMonth,
  getRolloversByEnvelope,
  deleteRollover,
  deleteRolloversByMonth,
  // V4 — Budget Alerts
  createBudgetAlert,
  getBudgetAlertById,
  getBudgetAlerts,
  getAlertsByEnvelope,
  updateBudgetAlert,
  deleteBudgetAlert,
  createAlertHistory,
  getAlertHistoryByAlert,
  getAlertHistoryByMonth,
  deleteAlertHistory,
  // V4 — Currencies & Exchange Rates
  createCurrency,
  getCurrency,
  getCurrencies,
  getBaseCurrency,
  deleteCurrency,
  upsertExchangeRate,
  getExchangeRate,
  getExchangeRates,
  deleteExchangeRate,
} from './db';

export {
  buildBudgetExportBundle,
  serializeBudgetExportJson,
  exportBudgetTransactionsCsv,
  resetBudgetData,
} from './portability';

export type {
  TransactionWithSplits,
  NetWorthSnapshotInsert,
  NetWorthSnapshotUpdate,
  BudgetRolloverInsert,
  AlertHistoryInsert,
  CurrencyInsert,
  ExchangeRateInsert,
} from './db';

// Subscription catalog
export {
  SUBSCRIPTION_CATALOG,
  searchCatalog,
  getPopularEntries,
  normalizeToMonthly,
  normalizeToAnnual,
  calculateNextRenewal,
} from './db/subscription-catalog';

// Subscription engine
export {
  advanceRenewalDate,
  getUpcomingRenewals,
  normalizeToDaily,
  calculateSubscriptionSummary,
  validateTransition,
  getValidTransitions,
  getRenewalNotifications,
  getTrialExpirationAlerts,
  getMonthlySummaryNotification,
  logNotification,
  cancelNotifications,
  getNotificationLog,
  recordPriceChange,
  getPriceHistory,
  getLifetimeCost,
  mapBillingCycleToFrequency,
  createSubscriptionTemplate,
  syncSubscriptionToTemplate,
  processRenewal,
  deactivateSubscriptionTemplate,
  reactivateSubscriptionTemplate,
} from './subscriptions';
export type {
  EnvelopeCostSummary,
  SubscriptionCostSummary,
  PendingNotification,
} from './subscriptions';

// Budget engine
export {
  // Core budget calculation
  calculateMonthBudget,
  getCarryForward,
  getTotalOverspent,
  moveMoneyBetweenCategories,
  // Allocation operations (DB-backed)
  allocateToEnvelope,
  moveAllocation,
  getAllocationsForMonth,
  getAllocationMap,
  // Schedule calculator
  calculateNextDate,
  generateOccurrences,
  // Transaction rules
  evaluateCondition,
  evaluateConditions,
  matchRule,
  applyRules,
  // Income estimator
  detectIncomeStreams,
  classifyIncomePattern,
  estimateMonthlyIncome,
  // Payday detector
  detectPaydays,
  predictNextPayday,
  getPaydaySchedule,
  // Net cash
  calculateNetCash,
  calculateCashFlowByPeriod,
  calculateRunningBalance,
  // Goal tracking
  calculateGoalProgress,
  suggestMonthlyContribution,
  isGoalOnTrack,
  getGoalStatus,
  calculateGoalProjection,
  // Reporting
  getSpendingByCategory,
  getMonthlySpendingTrend,
  getBudgetedVsSpent,
  getTopPayees,
  // Net worth
  calculateNetWorth,
  buildNetWorthTimeline,
  captureSnapshot,
  // Debt payoff
  calculateSnowball,
  calculateAvalanche,
  generateAmortizationSchedule,
  projectPayoffDate,
  // Rollover
  calculateRollover,
  processMonthRollover,
  applyRollovers,
  // Upcoming
  getUpcomingTransactions,
  groupByDate,
  getUpcomingTotal,
  // Alerts
  checkAlerts,
  shouldFireAlert,
  buildAlertNotification,
  // Multi-currency
  RATE_PRECISION,
  convertAmount,
  formatCurrencyAmount,
  convertToBase,
} from './engine';

export type {
  // Budget types
  CategoryBudgetState,
  GroupBudgetState,
  MonthBudgetState,
  MonthBudgetInput,
  // Schedule
  ScheduleFrequency,
  // Transaction rules
  RuleCondition,
  RuleAction,
  EngineTransactionRule,
  RuleTransactionInput,
  RuleMatch,
  ApplyRulesResult,
  ConditionField,
  ConditionOperator,
  ActionType,
  // Income estimator
  IncomeFrequency,
  IncomePattern,
  IncomeStream,
  IncomeEstimate,
  // Payday detector
  PaydayFrequency,
  PaydayPattern,
  PaydayPrediction,
  // Net cash
  NetCashResult,
  CashFlowPeriod,
  CashFlowPeriodType,
  RunningBalanceEntry,
  // Goals
  GoalInput,
  GoalProgress,
  GoalStatus,
  GoalProjection,
  // Reporting
  ReportCategorySpending,
  MonthlySpendingPoint,
  BudgetVsSpentRow,
  TopPayee,
  DateRange,
  // Net worth
  NetWorthAccountInput,
  NetWorthResult,
  NetWorthEngineSnapshot,
  NetWorthTimelinePoint,
  SnapshotInput,
  // Debt payoff
  DebtInput,
  EnginePayoffStrategy,
  PayoffScheduleEntry,
  DebtPayoffResult,
  AmortizationEntry,
  // Rollover
  RolloverRecord,
  RolloverInput,
  // Upcoming
  UpcomingTemplate,
  UpcomingTransaction,
  GroupedUpcoming,
  // Alerts
  AlertConfig,
  EngineAlertHistoryEntry,
  EnvelopeSpendState,
  AlertNotification,
  // Multi-currency
  CurrencyExchangeRate,
  CurrencyInfo,
} from './engine';
